### ISSUE TITLE
Message after auth close

### ISSUE THREAD

**Issue by wlingzhenyu** [LNSSPsd/PhoenixBuilder#321]
**This is a frequent mistake.The error is thrown almost every few minutes.**

```
Error: SendMessage: Connection closed
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x19
phoenixbuilder/solutions/fastbuilder.Fatal()
        phoenixbuilder/solutions/fastbuilder/fatal_control.go:32 +0x48
panic({0xa993c0, 0xcbaf40})
        runtime/panic.go:884 +0x213
phoenixbuilder/fastbuilder/cv4/auth.(*Client).SendMessage(0xa819c0?, {0xc0cd718500?, 0x0?, 0xc0000b57a0?})
        phoenixbuilder/fastbuilder/cv4/auth/client.go:151 +0x158
phoenixbuilder/fastbuilder/cv4/auth.(*Client).TransferCheckNum(0xc0003a9200, {0xc0cd716000, 0x2438})
        phoenixbuilder/fastbuilder/cv4/auth/client.go:335 +0x9c
phoenixbuilder/solutions/fastbuilder.EnterWorkerThread(0xc00084a000, 0x0)
        phoenixbuilder/solutions/fastbuilder/core.go:135 +0x8d9
phoenixbuilder/solutions/fastbuilder.runInteractiveClient({0xc000af4000, 0x98})
        phoenixbuilder/solutions/fastbuilder/bootstrap.go:105 +0x168
phoenixbuilder/solutions/fastbuilder.Bootstrap()
        phoenixbuilder/solutions/fastbuilder/bootstrap.go:79 +0xa5
main.main()
        phoenixbuilder/main.go:6 +0x17
 ERROR  FastBuilder Phoenix 运行过程遇到问题
 ERROR  Stack dump 于上方显示。错误为：
 ERROR  Message after auth close
```

**Comment by Happy2018new** [comment]
正在尝试修复此问题。
