### ISSUE TITLE
发生空指针解引用错误（nil pointer dereference）

### ISSUE THREAD

**Issue by wlingzhenyu** [LNSSPsd/PhoenixBuilder#327]
我在使用源代码go run main.go时，我得到了以下错误信息，就算构建make的程序也会抛出这个错误

```
INFO  [Auth Server] 欢迎, wling !
ERROR  %!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)
ERROR  按ENTER（回车）键来退出程序。

goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x19
phoenixbuilder/solutions/fastbuilder.Fatal()
        phoenixbuilder/solutions/fastbuilder/fatal_control.go:32 +0x5d
panic({0x1601880, 0xc00009c050})
        runtime/panic.go:884 +0x213
phoenixbuilder/solutions/fastbuilder.EstablishConnectionAndInitEnv(0xc000002d80)
        phoenixbuilder/solutions/fastbuilder/core.go:304 +0x172d
phoenixbuilder/solutions/fastbuilder.runInteractiveClient({0xc000044280, 0x98})
        phoenixbuilder/solutions/fastbuilder/bootstrap.go:102 +0xf7
phoenixbuilder/solutions/fastbuilder.Bootstrap()
        phoenixbuilder/solutions/fastbuilder/bootstrap.go:79 +0x97
main.main()
        phoenixbuilder/main.go:6 +0x17
ERROR  FastBuilder Phoenix 运行过程遇到问题
ERROR  Stack dump 于上方显示。错误为：
ERROR  %!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)
ERROR  按ENTER（回车）键来退出程序。
```

**复现：**
输入完密码后，出现 INFO  [Auth Server] 欢迎, xxx！
抛出空指针错误

**期望行为：**
成功连接服务器

**Comment by Happy2018new** [comment]
这并非是一个 `Bug` ，而是 `Raknet` 的协议不同所致。

首先你需要找到 `Go` 存放软件包的目录（不是安装目录），对于 `Termux` 来说，它默认生成在 `~/go/pkg` 目录下；对于 `Windows` 来说，它默认生成在 `%USERPROFILE%/go/pkg` 下。

然后，在该文件夹下找到 `mod/github.com/sandertv/go-raknet@v1.9.1/conn.go` 这个文件，将其中 `17` 行的 `currentProtocol byte = 10` 修改为 `currentProtocol byte = 8` ，如下图所示。

改完后保存，然后重新编译 `PhoenixBuilder` 并运行，报错消失。

***

<img width="960" alt="image" src="https://github.com/LNSSPsd/PhoenixBuilder/assets/109064184/110ea528-5b02-40cd-ac13-5ba835751c9a">

**Comment by Happy2018new** [comment]
用户中心中给出了 `Linux` 下关于 `PhoenixBuilder` 的编译方法。

<img width="647" alt="image" src="https://github.com/LNSSPsd/PhoenixBuilder/assets/109064184/df788053-8420-4104-8553-347a20de0819">

**Comment by Happy2018new** [comment]
那么此议题作为 `未计划` 而关闭，如有其他问题，届时再重新打开其。
