### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by IXBOB** [LNSSPsd/PhoenixBuilder#342]
Warning: Feature readline is not compatible with current platform.
┌───────────────────────────────────────────┐
| https://github.com/LNSSPsd/PhoenixBuilder |
└───────────────────────────────────────────┘
PhoenixBuilder
已启用语言：简体中文
正在检查更新，请稍等…完成
输入你的FastBuilder用户中心用户名: IXBOB
请输入你的FastBuilder用户中心登录密码(不会显示):
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x83
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x1a
phoenixbuilder/solutions/fastbuilder.Fatal()
        phoenixbuilder/solutions/fastbuilder/fatal_control.go:32 +0x5f
panic({0xccae00, 0x13807be8})
        runtime/panic.go:838 +0x1ba
phoenixbuilder/fastbuilder/pv4.CreateClient(0x151691b0)
        phoenixbuilder/fastbuilder/pv4/client.go:79 +0x22d
phoenixbuilder/solutions/fastbuilder.ConfigRealEnvironment({0x0, 0x0}, {0x11ffe24, 0x0}, {0x11ffe24, 0x0}, {0x1526ae20, 0x5}, {0x139c5f00, 0x40})
        phoenixbuilder/solutions/fastbuilder/env.go:77 +0xc7
phoenixbuilder/solutions/fastbuilder.runInteractiveClient({0x0, 0x0}, {0x1526ae20, 0x5}, {0x139c5f00, 0x40})
        phoenixbuilder/solutions/fastbuilder/bootstrap.go:96 +0x117
phoenixbuilder/solutions/fastbuilder.Bootstrap()
        phoenixbuilder/solutions/fastbuilder/bootstrap.go:79 +0xa7
main.main()
        phoenixbuilder/main.go:6 +0x17
 ERROR  FastBuilder Phoenix 运行过程遇到问题
 ERROR  Stack dump 于上方显示。错误为：
 ERROR  Failed to contact with API
 ERROR  按ENTER（回车）键来退出程序。

**Comment by IXBOB** [comment]
运行环境 Windows 10 22H2

**Comment by IXBOB** [comment]
版本 5.6.1 Windows x64 exe文件

**Comment by IXBOB** [comment]
眼瞎运行了x86版
