### ISSUE TITLE
export功能错误

### ISSUE THREAD

**Issue by HDTianRu** [LNSSPsd/PhoenixBuilder#348]
当使用导出(export)时的"开始点"与"结束点"的z轴都为负数时（在我测试时）
将会报错，详细报错如下

> set 0 0 -10
已设定坐标: 0, 0, -10.
> setend 0 0 -20
已设定终点坐标: 0, 0, -20.
> export -p acb
goroutine 28 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x68
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x20
phoenixbuilder/solutions/fastbuilder.Fatal()
        phoenixbuilder/solutions/fastbuilder/fatal_control.go:32 +0x78
panic({0x56cc1741e0, 0x56cc561da0})
        runtime/panic.go:838 +0x204
phoenixbuilder/fastbuilder/task/fetcher.PlanHopSwapPath(0x40006235e0?, 0xd?, 0x400161e100?, 0x56cbb6cb08?, 0x40000840c0?)
        phoenixbuilder/fastbuilder/task/fetcher/planner.go:76 +0x518
phoenixbuilder/io/special_tasks.CreateExportTask({0x40006235e0, 0xd}, 0x4000703040)
        phoenixbuilder/io/special_tasks/export.go:60 +0x14c
phoenixbuilder/fastbuilder/function.InitPresetFunctions.func23(0x4000703040, {0x40006235e0?, 0x40006235e0?})
        phoenixbuilder/fastbuilder/function/presets.go:433 +0x38
phoenixbuilder/fastbuilder/function.(*FunctionHolder).Process(0x4001d05ef0, {0x40006235e0, 0xd})
        phoenixbuilder/fastbuilder/function/function.go:84 +0x1e8
phoenixbuilder/solutions/fastbuilder.EnterReadlineThread(0x4000703040, 0x0)
        phoenixbuilder/solutions/fastbuilder/core.go:82 +0x4a0
created by phoenixbuilder/solutions/fastbuilder.runInteractiveClient
        phoenixbuilder/solutions/fastbuilder/bootstrap.go:103 +0x18c
 ERROR  FastBuilder Phoenix 运行过程遇到问题
 ERROR  Stack dump 于上方显示。错误为：
 ERROR  runtime error: invalid memory address or nil pointer dereference

我分别测试了
0 0 -10至0 0 -10(报错)
0 0 0至0 0 0(不报错)
114 0 -10至114 0 -20(报错)
114 0 514至110 0 543(不报错)

fb版本：最新main分支release
测试平台：安卓和windows

**Comment by Happy2018new** [comment]
Confirmed, but I have no idea about that.  However, now I have no time to find the reason and fix it.

**Comment by Happy2018new** [comment]
原有的修复是不正确的，因此现在将此议题重新打开。
